
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${DATABASE_CONNECTING_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    service-url:
      default-zone: ${SERVICE_REGISTRY_EUREKA}
